DROP TYPE IF EXISTS cartline;
CREATE TYPE cartline AS ENUM ('PRODUCT', 'RECIPE');

CREATE TABLE carts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at     TIMESTAMP(6)   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP(6)   NOT NULL DEFAULT NOW(),
    deleted_at     TIMESTAMP(6),
    total_in_cents NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    PRIMARY KEY (id)
);

CREATE TABLE products
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at     TIMESTAMP(6)   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP(6)   NOT NULL DEFAULT NOW(),
    deleted_at     TIMESTAMP(6),
    name           VARCHAR(255)   NOT NULL,
    price_in_cents NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    PRIMARY KEY (id)
);

CREATE TABLE recipe
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at     TIMESTAMP(6)   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP(6)   NOT NULL DEFAULT NOW(),
    deleted_at     TIMESTAMP(6),
    name           VARCHAR(255)   NOT NULL,
    description    VARCHAR(255)   NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE cart_recipes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP(6),
    cart_id    BIGINT       NOT NULL,
    recipe_id  BIGINT       NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE recipe_ingredient
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP(6),
    product_id BIGINT       NOT NULL,
    recipe_id  BIGINT       NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ux_recipe_ingredient_recipe_product UNIQUE (recipe_id, product_id)
);

CREATE TABLE cart_items
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at     TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    deleted_at     TIMESTAMP(6),
    cart_id        BIGINT       NOT NULL,
    product_id     BIGINT,
    cart_recipe_id BIGINT,
    line_type      cartline     NOT NULL DEFAULT 'PRODUCT',
    quantity       BIGINT       NOT NULL,
    PRIMARY KEY (id)
);


ALTER TABLE IF EXISTS cart_recipes ADD CONSTRAINT FKpauuei83jshaei12mka FOREIGN KEY (cart_id) REFERENCES carts;
ALTER TABLE IF EXISTS cart_recipes ADD CONSTRAINT FKpazz1aloei12mkaqo01 FOREIGN KEY (recipe_id) REFERENCES recipe;
ALTER TABLE IF EXISTS recipe_ingredient ADD CONSTRAINT FKpalowertyi12mkaqaqw FOREIGN KEY (product_id) REFERENCES products;
ALTER TABLE IF EXISTS recipe_ingredient ADD CONSTRAINT FKpalowertyalowippoae FOREIGN KEY (recipe_id) REFERENCES recipe;
ALTER TABLE IF EXISTS cart_items ADD CONSTRAINT FKpaloweapow9827yeb28 FOREIGN KEY (cart_id) REFERENCES carts;
ALTER TABLE IF EXISTS cart_items ADD CONSTRAINT FKpaloweapo0123iuje8n FOREIGN KEY (product_id) REFERENCES products;
ALTER TABLE IF EXISTS cart_items ADD CONSTRAINT FKpaloweapo1109oiwju3 FOREIGN KEY (cart_recipe_id) REFERENCES cart_recipes;



