spring:
  application:
    name: buy-recipes
  datasource:
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/buyrecipe?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: buy-recipe-main
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/buyrecipe
    user: postgres
    password: postgres
  jmx:
    enabled: false

logging:
  level:
    root: info
    com.zaxxer.hikari: warn
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.hibernate.orm.connections.pooling: warn
